apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    uid: gcp-monitoring
    type: stackdriver
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      authenticationType: jwt
      clientEmail: ${GCP_SA_CLIENT_EMAIL}
      defaultProject: ${GCP_PROJECT_ID}
      tokenUri: https://oauth2.googleapis.com/token
      privateKeyPath: /etc/secrets/gcp/grafana-gcp-key.pem
